apiVersion: gollum.soeren.cloud/v1alpha1
kind: Repository
metadata:
  labels:
    app.kubernetes.io/name: gollum
    app.kubernetes.io/managed-by: kustomize
  name: repository-sample
spec:
  # TODO(user): Add fields here
